#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Motor,  mtr_Matrix_S1_1, crank,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2, motor_left,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3, motor_right,   tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4, motorG,        tmotorMatrix, openLoop)
#pragma config(Servo,  srvo_Matrix_S1_1, servo1,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_2, servo2,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_3, servo3,               tServoNone)
#pragma config(Servo,  srvo_Matrix_S1_4, servo4,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.



	while (true)
	{
		motor[motor_left] = 100;
		motor[motor_right] = 100;
		wait1Msec(3000);
		motor[motor_left] = 100;
		motor[motor_right] = -100;
		wait1Msec(3000);
		motor[motor_left] = 100;
		motor[motor_right] = 100;
		wait1Msec(3000);
		motor[motor_left] = 0;
		motor[motor_left] = 0;
		wait10Msec(300000);
	}
}
